// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace za {

static const char* SAD_method_names[] = {
  "/za.SAD/validate",
};

std::unique_ptr< SAD::Stub> SAD::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SAD::Stub> stub(new SAD::Stub(channel, options));
  return stub;
}

SAD::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_validate_(SAD_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SAD::Stub::validate(::grpc::ClientContext* context, const ::za::AudioRequest& request, ::za::AnomalyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::za::AudioRequest, ::za::AnomalyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_validate_, context, request, response);
}

void SAD::Stub::async::validate(::grpc::ClientContext* context, const ::za::AudioRequest* request, ::za::AnomalyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::za::AudioRequest, ::za::AnomalyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_validate_, context, request, response, std::move(f));
}

void SAD::Stub::async::validate(::grpc::ClientContext* context, const ::za::AudioRequest* request, ::za::AnomalyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_validate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::za::AnomalyReply>* SAD::Stub::PrepareAsyncvalidateRaw(::grpc::ClientContext* context, const ::za::AudioRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::za::AnomalyReply, ::za::AudioRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_validate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::za::AnomalyReply>* SAD::Stub::AsyncvalidateRaw(::grpc::ClientContext* context, const ::za::AudioRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncvalidateRaw(context, request, cq);
  result->StartCall();
  return result;
}

SAD::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SAD_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SAD::Service, ::za::AudioRequest, ::za::AnomalyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SAD::Service* service,
             ::grpc::ServerContext* ctx,
             const ::za::AudioRequest* req,
             ::za::AnomalyReply* resp) {
               return service->validate(ctx, req, resp);
             }, this)));
}

SAD::Service::~Service() {
}

::grpc::Status SAD::Service::validate(::grpc::ServerContext* context, const ::za::AudioRequest* request, ::za::AnomalyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace za

