// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_service_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_service_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_service_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_service_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_service_2eproto;
namespace za {
class AnomalyReply;
struct AnomalyReplyDefaultTypeInternal;
extern AnomalyReplyDefaultTypeInternal _AnomalyReply_default_instance_;
class AudioRequest;
struct AudioRequestDefaultTypeInternal;
extern AudioRequestDefaultTypeInternal _AudioRequest_default_instance_;
}  // namespace za
PROTOBUF_NAMESPACE_OPEN
template<> ::za::AnomalyReply* Arena::CreateMaybeMessage<::za::AnomalyReply>(Arena*);
template<> ::za::AudioRequest* Arena::CreateMaybeMessage<::za::AudioRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace za {

// ===================================================================

class AudioRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:za.AudioRequest) */ {
 public:
  inline AudioRequest() : AudioRequest(nullptr) {}
  ~AudioRequest() override;
  explicit PROTOBUF_CONSTEXPR AudioRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AudioRequest(const AudioRequest& from);
  AudioRequest(AudioRequest&& from) noexcept
    : AudioRequest() {
    *this = ::std::move(from);
  }

  inline AudioRequest& operator=(const AudioRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioRequest& operator=(AudioRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudioRequest* internal_default_instance() {
    return reinterpret_cast<const AudioRequest*>(
               &_AudioRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AudioRequest& a, AudioRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AudioRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudioRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AudioRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AudioRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AudioRequest& from) {
    AudioRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudioRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "za.AudioRequest";
  }
  protected:
  explicit AudioRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAudioBytesFieldNumber = 1,
  };
  // bytes audioBytes = 1;
  void clear_audiobytes();
  const std::string& audiobytes() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_audiobytes(ArgT0&& arg0, ArgT... args);
  std::string* mutable_audiobytes();
  PROTOBUF_NODISCARD std::string* release_audiobytes();
  void set_allocated_audiobytes(std::string* audiobytes);
  private:
  const std::string& _internal_audiobytes() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_audiobytes(const std::string& value);
  std::string* _internal_mutable_audiobytes();
  public:

  // @@protoc_insertion_point(class_scope:za.AudioRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr audiobytes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};
// -------------------------------------------------------------------

class AnomalyReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:za.AnomalyReply) */ {
 public:
  inline AnomalyReply() : AnomalyReply(nullptr) {}
  ~AnomalyReply() override;
  explicit PROTOBUF_CONSTEXPR AnomalyReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AnomalyReply(const AnomalyReply& from);
  AnomalyReply(AnomalyReply&& from) noexcept
    : AnomalyReply() {
    *this = ::std::move(from);
  }

  inline AnomalyReply& operator=(const AnomalyReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnomalyReply& operator=(AnomalyReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnomalyReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnomalyReply* internal_default_instance() {
    return reinterpret_cast<const AnomalyReply*>(
               &_AnomalyReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AnomalyReply& a, AnomalyReply& b) {
    a.Swap(&b);
  }
  inline void Swap(AnomalyReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnomalyReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnomalyReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AnomalyReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AnomalyReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AnomalyReply& from) {
    AnomalyReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnomalyReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "za.AnomalyReply";
  }
  protected:
  explicit AnomalyReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIsValidFieldNumber = 1,
  };
  // bool isValid = 1;
  void clear_isvalid();
  bool isvalid() const;
  void set_isvalid(bool value);
  private:
  bool _internal_isvalid() const;
  void _internal_set_isvalid(bool value);
  public:

  // @@protoc_insertion_point(class_scope:za.AnomalyReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool isvalid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AudioRequest

// bytes audioBytes = 1;
inline void AudioRequest::clear_audiobytes() {
  _impl_.audiobytes_.ClearToEmpty();
}
inline const std::string& AudioRequest::audiobytes() const {
  // @@protoc_insertion_point(field_get:za.AudioRequest.audioBytes)
  return _internal_audiobytes();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AudioRequest::set_audiobytes(ArgT0&& arg0, ArgT... args) {
 
 _impl_.audiobytes_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:za.AudioRequest.audioBytes)
}
inline std::string* AudioRequest::mutable_audiobytes() {
  std::string* _s = _internal_mutable_audiobytes();
  // @@protoc_insertion_point(field_mutable:za.AudioRequest.audioBytes)
  return _s;
}
inline const std::string& AudioRequest::_internal_audiobytes() const {
  return _impl_.audiobytes_.Get();
}
inline void AudioRequest::_internal_set_audiobytes(const std::string& value) {
  
  _impl_.audiobytes_.Set(value, GetArenaForAllocation());
}
inline std::string* AudioRequest::_internal_mutable_audiobytes() {
  
  return _impl_.audiobytes_.Mutable(GetArenaForAllocation());
}
inline std::string* AudioRequest::release_audiobytes() {
  // @@protoc_insertion_point(field_release:za.AudioRequest.audioBytes)
  return _impl_.audiobytes_.Release();
}
inline void AudioRequest::set_allocated_audiobytes(std::string* audiobytes) {
  if (audiobytes != nullptr) {
    
  } else {
    
  }
  _impl_.audiobytes_.SetAllocated(audiobytes, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.audiobytes_.IsDefault()) {
    _impl_.audiobytes_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:za.AudioRequest.audioBytes)
}

// -------------------------------------------------------------------

// AnomalyReply

// bool isValid = 1;
inline void AnomalyReply::clear_isvalid() {
  _impl_.isvalid_ = false;
}
inline bool AnomalyReply::_internal_isvalid() const {
  return _impl_.isvalid_;
}
inline bool AnomalyReply::isvalid() const {
  // @@protoc_insertion_point(field_get:za.AnomalyReply.isValid)
  return _internal_isvalid();
}
inline void AnomalyReply::_internal_set_isvalid(bool value) {
  
  _impl_.isvalid_ = value;
}
inline void AnomalyReply::set_isvalid(bool value) {
  _internal_set_isvalid(value);
  // @@protoc_insertion_point(field_set:za.AnomalyReply.isValid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace za

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_service_2eproto
